### PR TITLE
Creating dependabot for dependency updating

### PR DESCRIPTION
**Pull request by git-elliot**
Adding dependabot for updating dependencies.

### CODE REVIEW

**Comment by guyluz11** [comment]
Looks cool, I don't have time to test it but the code looks ok

**Comment by git-elliot** [comment]
Approve this PR @guyluz11

**Comment by guyluz11** [comment]
> Approve this PR @guyluz11

You didn't change the pr to deb branch.

And I can't approve a PR like that if I don't test that it works first.

So just merged it if you testes it

**Comment by git-elliot** [comment]
@guyluz11 how come just changing the branch added more files. I didn't added these files. I'll remove soon

**Comment by guyluz11** [comment]
Because those files were added to master and not Dev branche

And you forked your brach from master

**Comment by git-elliot** [comment]
Ohh okay then I will remove these files in local and push again

**Comment by guyluz11** [comment]
This is not the correct way to fix it, you need to resolve the conflicts

**Comment by git-elliot** [comment]
I'll resolve conflicts. No problem.

**Comment by git-elliot** [comment]
@guyluz11 does it looks fine now.

**Comment by guyluz11** [comment]
Looks good good 👍

I think `interval: "weekly"` will be a lot of work to test it each time manually.
But I guess you are prepared for that and we can always change that

**Pull request merged**
