### PR TITLE
Remove analyzer warnings

### PR DESCRIPTION
**Pull request by JSmurf**
Fixes issue #47

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi @JSmurf , can you please change pr to branch dev?

**Comment by JSmurf** [comment]
Hey @guyluz11, I'm wondering if it might be easier to just close this PR and open a new one with the new branch I made?

**Comment by guyluz11** [comment]
> Hey @guyluz11, I'm wondering if it might be easier to just close this PR and open a new one with the new branch I made?
> 
> Seems easier than resolving the conflicts.

Please do, you have conflicts to fix and it will help.

And you need to write in the issue that you want to work on it.
Otherwise we will assign other people to this issue and it will create a mess.

**Comment by JSmurf** [comment]
Sounds good. Closing this one.

**Pull request closed without merging**
